referee: [European Journal of Operational Research, Journal of Banking and Finance, Journal of Corporate Finance, Journal of Economic Theory, Journal of Finance, Journal of Financial and Quantitative Analysis, Journal of the European Economic Association, Management Science, Review of Economic Studies, Review of Economics and Statistics, Review of Financial Studies]
institutional:
  - Member, Haskayne Teaching with AI Working Group, Fall 2026
  - Member, Degree Committee, Bocconi Data Science MSc
  - Member, Program Design Committee, Bocconi Data Science MSc
  - Organizer, Bocconi Finance Seminar Series
conferences:
  - Scientific Committee Member, EFA Conference 2023
  - Co-organizer, Financial Intermediation Workshop, 2022 (with Eva Schliephake)
  - Scientific Committee Member, EFA Conference 2022
  - Local Scientific Committee, EFA Conference, 2021
  - Organizer, European Junior Banking Online Seminar Series, 2021–2023 (with Eva Schliephake)
  - Co-organizer, EuroFIT Conference, December 2018 (with Frederic Malherbe)
